CREATE TABLE "users" (
  "user_id" UUID PRIMARY KEY,
  "username" "VARCHAR(255)" UNIQUE,
  "email" "VARCHAR(255)" UNIQUE,
  "password_hash" "VARCHAR(255)",
  "status" "VARCHAR(255)" DEFAULT 'ACTIVE',
  "created_at" "TIMESTAMPTZ" DEFAULT (now()),
  "updated_at" "TIMESTAMPTZ" DEFAULT (now())
);

CREATE TABLE "roles" (
  "role_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" "VARCHAR(100)" UNIQUE NOT NULL,
  "name" "VARCHAR(255)" NOT NULL,
  "description" TEXT,
  "created_at" "TIMESTAMPTZ" NOT NULL DEFAULT (now())
);

CREATE TABLE "user_roles" (
  "user_id" UUID NOT NULL,
  "role_id" integer NOT NULL,
  "assigned_at" timestamptz NOT NULL DEFAULT (now()),
  PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "permissions" (
  "permission_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resource" varchar(50) NOT NULL,
  "action" varchar(50) NOT NULL,
  "code" varchar(120) UNIQUE,
  "description" text,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "role_permissions" (
  "role_id" integer NOT NULL,
  "permission_id" integer NOT NULL,
  PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE "user_reputations" (
  "user_id" UUID UNIQUE PRIMARY KEY,
  "score" integer DEFAULT 0,
  "level" varchar(50),
  "updated_at" timestamptz
);

CREATE TABLE "organizations" (
  "organization_id" UUID PRIMARY KEY,
  "name" varchar(255),
  "type" varchar(50),
  "address" text,
  "phone" varchar(50),
  "latitude" double,
  "longitude" double,
  "status" varchar,
  "created_at" timestamptz,
  "created_by" UUID
);

CREATE TABLE "shelters" (
  "organization_id" UUID
);

CREATE TABLE "vet_centers" (
  "organization_id" UUID
);

CREATE TABLE "adoption_applications" (
  "application_id" UUID PRIMARY KEY,
  "pet_id" UUID,
  "applicant_id" UUID,
  "organization_id" UUID,
  "status" varchar(50),
  "note" text,
  "created_at" timestamptz,
  "decided_at" timestamptz,
  "decided_by" UUID
);

CREATE TABLE "organization_members" (
  "organization_id" UUID,
  "user_id" UUID,
  "role" varchar,
  "joined_at" timestamptz,
  "status" varchar,
  PRIMARY KEY ("organization_id", "user_id")
);

CREATE TABLE "pet_caretaker_assignments" (
  "assignment_id" UUID PRIMARY KEY,
  "pet_id" UUID NOT NULL,
  "organization_id" UUID NOT NULL,
  "caretaker_id" UUID NOT NULL,
  "role" varchar(30),
  "assigned_at" timestamptz,
  "unassigned_at" timestamptz
);

CREATE TABLE "pets" (
  "pet_id" UUID PRIMARY KEY,
  "name" varchar(255),
  "species" varchar(100),
  "breed" varchar(255),
  "is_sterilized" boolean,
  "is_vaccinated" boolean,
  "color" varchar(255),
  "weight" double,
  "gender" varchar(50),
  "birth_date" date,
  "status" varchar(50),
  "description" text,
  "created_at" timestamptz
);

CREATE TABLE "pet_ownerships" (
  "pet_id" UUID,
  "owner_type" varchar(20),
  "owner_id" UUID,
  "from_time" timestamptz,
  "to_time" timestamptz,
  PRIMARY KEY ("pet_id", "from_time")
);

CREATE TABLE "pet_medical_records" (
  "record_id" UUID PRIMARY KEY,
  "pet_id" UUID NOT NULL,
  "description" text,
  "vaccine" varchar(255),
  "diagnosis" text,
  "record_date" timestamptz,
  "created_by" UUID
);

CREATE TABLE "pet_locations" (
  "location_id" UUID PRIMARY KEY,
  "pet_id" UUID NOT NULL,
  "latitude" double,
  "longitude" double,
  "source" varchar(50),
  "recorded_at" timestamptz
);

CREATE TABLE "rescue_cases" (
  "case_id" UUID PRIMARY KEY,
  "pet_id" UUID,
  "reported_by" UUID,
  "organization_id" UUID,
  "status" varchar(50),
  "reported_at" timestamptz
);

CREATE TABLE "posts" (
  "post_id" UUID PRIMARY KEY,
  "author_id" UUID,
  "rescue_case_id" UUID,
  "content" text,
  "created_at" timestamptz,
  "updated_at" timestamptz
);

CREATE TABLE "media_files" (
  "media_id" UUID PRIMARY KEY,
  "uploader_id" UUID,
  "url" text,
  "type" varchar(20),
  "created_at" timestamptz
);

CREATE TABLE "post_media" (
  "post_id" UUID,
  "media_id" UUID,
  PRIMARY KEY ("post_id", "media_id")
);

CREATE TABLE "pet_diary" (
  "pet_id" UUID,
  "media_id" UUID
);

CREATE TABLE "tags" (
  "tag_id" UUID PRIMARY KEY,
  "code" varchar(100) UNIQUE,
  "name" varchar(255),
  "description" text,
  "created_at" timestamptz
);

CREATE TABLE "post_tags" (
  "post_id" UUID,
  "tag_id" UUID,
  PRIMARY KEY ("post_id", "tag_id")
);

CREATE INDEX "idx_users_status" ON "users" ("status");

CREATE UNIQUE INDEX ON "permissions" ("resource", "action");

CREATE INDEX ON "pet_caretaker_assignments" ("pet_id", "caretaker_id", "assigned_at");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "user_roles" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("role_id");

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("permission_id");

ALTER TABLE "user_reputations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "organizations" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "shelters" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("organization_id");

ALTER TABLE "vet_centers" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("organization_id");

ALTER TABLE "adoption_applications" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "adoption_applications" ADD FOREIGN KEY ("applicant_id") REFERENCES "users" ("user_id");

ALTER TABLE "adoption_applications" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("organization_id");

ALTER TABLE "adoption_applications" ADD FOREIGN KEY ("decided_by") REFERENCES "users" ("user_id");

ALTER TABLE "organization_members" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("organization_id");

ALTER TABLE "organization_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "pet_caretaker_assignments" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "pet_caretaker_assignments" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("organization_id");

ALTER TABLE "pet_caretaker_assignments" ADD FOREIGN KEY ("caretaker_id") REFERENCES "users" ("user_id");

ALTER TABLE "pet_ownerships" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "pet_medical_records" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "pet_medical_records" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("user_id");

ALTER TABLE "pet_locations" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "rescue_cases" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "rescue_cases" ADD FOREIGN KEY ("reported_by") REFERENCES "users" ("user_id");

ALTER TABLE "rescue_cases" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("organization_id");

ALTER TABLE "posts" ADD FOREIGN KEY ("author_id") REFERENCES "users" ("user_id");

ALTER TABLE "posts" ADD FOREIGN KEY ("rescue_case_id") REFERENCES "rescue_cases" ("case_id");

ALTER TABLE "media_files" ADD FOREIGN KEY ("uploader_id") REFERENCES "users" ("user_id");

ALTER TABLE "post_media" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("post_id");

ALTER TABLE "post_media" ADD FOREIGN KEY ("media_id") REFERENCES "media_files" ("media_id");

ALTER TABLE "pet_diary" ADD FOREIGN KEY ("pet_id") REFERENCES "pets" ("pet_id");

ALTER TABLE "pet_diary" ADD FOREIGN KEY ("media_id") REFERENCES "media_files" ("media_id");

ALTER TABLE "post_tags" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("post_id");

ALTER TABLE "post_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("tag_id");
