-- ============================================================
-- V1: Consolidated schema — Pet Rescue API
-- All tables with full audit fields, PostGIS support
-- ============================================================

-- ── Enable PostGIS ──────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS postgis;

-- ── Users & Auth ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    user_id         UUID PRIMARY KEY,
    username        VARCHAR(255) UNIQUE NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    password_hash   VARCHAR(255),
    full_name       VARCHAR(255),
    avatar_url      TEXT,
    phone           VARCHAR(50),
    gender          VARCHAR(20),
    street_address  TEXT,
    ward_code       VARCHAR(20),
    ward_name       VARCHAR(255),
    province_code   VARCHAR(20),
    province_name   VARCHAR(255),
    status          VARCHAR(50)  NOT NULL DEFAULT 'PENDING_VERIFICATION',
    email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      UUID,
    updated_at      TIMESTAMPTZ  DEFAULT now(),
    updated_by      UUID,
    is_deleted      BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID
);

CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);
CREATE INDEX IF NOT EXISTS idx_users_email  ON users (email);

CREATE TABLE IF NOT EXISTS roles (
    role_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) UNIQUE NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  UUID,
    updated_at  TIMESTAMPTZ,
    updated_by  UUID,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    deleted_by  UUID
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id     UUID    NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    role_id     INTEGER NOT NULL REFERENCES roles (role_id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_user_roles_user ON user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON user_roles (role_id);

CREATE TABLE IF NOT EXISTS permissions (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource      VARCHAR(50)  NOT NULL,
    action        VARCHAR(50)  NOT NULL,
    code          VARCHAR(120) UNIQUE,
    description   TEXT,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (resource, action)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       INTEGER NOT NULL REFERENCES roles (role_id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES permissions (permission_id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_role_permissions_role ON role_permissions (role_id);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID         NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    token       VARCHAR(512) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  UUID,
    updated_at  TIMESTAMPTZ,
    updated_by  UUID,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    deleted_by  UUID
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user  ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON refresh_tokens (token);

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID         NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    token       VARCHAR(512) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  UUID,
    updated_at  TIMESTAMPTZ,
    updated_by  UUID,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    deleted_by  UUID
);

CREATE TABLE IF NOT EXISTS user_reputations (
    user_id    UUID PRIMARY KEY REFERENCES users (user_id) ON DELETE CASCADE,
    score      INTEGER     DEFAULT 0,
    level      VARCHAR(50),
    updated_at TIMESTAMPTZ
);

-- ── Organizations ───────────────────────────────────────

CREATE TABLE IF NOT EXISTS organizations (
    organization_id UUID PRIMARY KEY,
    name            VARCHAR(255),
    type            VARCHAR(50),
    street_address  TEXT,
    province_code   VARCHAR(20),
    province_name   VARCHAR(255),
    ward_code       VARCHAR(20),
    ward_name       VARCHAR(255),
    location        geometry(Point,4326),
    phone           VARCHAR(50),
    email           VARCHAR(255),
    official_link   TEXT,
    status          VARCHAR(50),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID REFERENCES users (user_id),
    updated_at      TIMESTAMPTZ,
    updated_by      UUID,
    is_deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID
);

CREATE INDEX IF NOT EXISTS idx_org_type     ON organizations (type);
CREATE INDEX IF NOT EXISTS idx_org_province ON organizations (province_code);
CREATE INDEX IF NOT EXISTS idx_org_location ON organizations USING GIST (location);

CREATE TABLE IF NOT EXISTS organization_members (
    organization_id UUID        NOT NULL REFERENCES organizations (organization_id) ON DELETE CASCADE,
    user_id         UUID        NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    role            VARCHAR(30),
    joined_at       TIMESTAMPTZ,
    status          VARCHAR(50),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID,
    updated_at      TIMESTAMPTZ,
    updated_by      UUID,
    is_deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID,
    PRIMARY KEY (organization_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_org_members_user ON organization_members (user_id);

-- ── Pets ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pets (
    pet_id          UUID PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    species         VARCHAR(100) NOT NULL,
    breed           VARCHAR(255),
    age             INTEGER,
    gender          VARCHAR(50),
    color           VARCHAR(255),
    weight          NUMERIC(5,2),
    description     TEXT,
    status          VARCHAR(50) NOT NULL,
    health_status   VARCHAR(30),
    is_vaccinated   BOOLEAN     NOT NULL DEFAULT FALSE,
    is_neutered     BOOLEAN     NOT NULL DEFAULT FALSE,
    rescue_date     DATE,
    rescue_location VARCHAR(255),
    shelter_id      UUID,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID,
    updated_at      TIMESTAMPTZ,
    updated_by      UUID,
    is_deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID
);

CREATE INDEX IF NOT EXISTS idx_pets_species ON pets (species);
CREATE INDEX IF NOT EXISTS idx_pets_status  ON pets (status);
CREATE INDEX IF NOT EXISTS idx_pets_color   ON pets (color);
CREATE INDEX IF NOT EXISTS idx_pets_shelter ON pets (shelter_id);

CREATE TABLE IF NOT EXISTS pet_media (
    media_id   UUID PRIMARY KEY,
    pet_id     UUID NOT NULL REFERENCES pets (pet_id) ON DELETE CASCADE,
    url        TEXT,
    type       VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pet_media_pet ON pet_media (pet_id);

CREATE TABLE IF NOT EXISTS pet_ownerships (
    pet_id     UUID        NOT NULL REFERENCES pets (pet_id) ON DELETE CASCADE,
    owner_type VARCHAR(20),
    owner_id   UUID,
    from_time  TIMESTAMPTZ NOT NULL,
    to_time    TIMESTAMPTZ,
    PRIMARY KEY (pet_id, from_time)
);

CREATE INDEX IF NOT EXISTS idx_pet_owner_owner ON pet_ownerships (owner_id);

CREATE TABLE IF NOT EXISTS pets_current_owner (
    pet_id     UUID PRIMARY KEY REFERENCES pets (pet_id),
    owner_type VARCHAR(20),
    owner_id   UUID
);

CREATE INDEX IF NOT EXISTS idx_current_owner_owner ON pets_current_owner (owner_id);

CREATE TABLE IF NOT EXISTS pet_medical_records (
    record_id   UUID PRIMARY KEY,
    pet_id      UUID NOT NULL REFERENCES pets (pet_id) ON DELETE CASCADE,
    description TEXT,
    vaccine     VARCHAR(255),
    diagnosis   TEXT,
    record_date TIMESTAMPTZ,
    created_by  UUID REFERENCES users (user_id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ,
    updated_by  UUID,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    deleted_by  UUID
);

CREATE INDEX IF NOT EXISTS idx_pet_medical_pet ON pet_medical_records (pet_id);

-- ── Media Files ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS media_files (
    media_id      UUID PRIMARY KEY,
    uploader_id   UUID REFERENCES users (user_id),
    public_id     VARCHAR(255) UNIQUE NOT NULL,
    resource_type VARCHAR(20),
    format        VARCHAR(20),
    width         INTEGER,
    height        INTEGER,
    bytes         INTEGER,
    folder        VARCHAR(255),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    UUID,
    updated_at    TIMESTAMPTZ,
    updated_by    UUID,
    is_deleted    BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    deleted_by    UUID
);

CREATE INDEX IF NOT EXISTS idx_media_uploader  ON media_files (uploader_id);
CREATE INDEX IF NOT EXISTS idx_media_public_id ON media_files (public_id);

-- ── Rescue Cases ────────────────────────────────────────

CREATE TABLE IF NOT EXISTS rescue_cases (
    case_id         UUID PRIMARY KEY,
    reported_by     UUID REFERENCES users (user_id),
    organization_id UUID REFERENCES organizations (organization_id),
    pet_id          UUID REFERENCES pets (pet_id),
    species         VARCHAR(100),
    color           VARCHAR(100),
    size            VARCHAR(50),
    condition       VARCHAR(50),
    description     TEXT,
    location        geometry(Point,4326),
    location_text   TEXT,
    province_code   VARCHAR(50),
    ward_code       VARCHAR(50),
    status          VARCHAR(50),
    reported_at     TIMESTAMPTZ,
    resolved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID,
    updated_at      TIMESTAMPTZ,
    updated_by      UUID,
    is_deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID
);

CREATE INDEX IF NOT EXISTS idx_rescue_location    ON rescue_cases USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_rescue_status      ON rescue_cases (status);
CREATE INDEX IF NOT EXISTS idx_rescue_species     ON rescue_cases (species);
CREATE INDEX IF NOT EXISTS idx_rescue_reported_at ON rescue_cases (reported_at);

CREATE TABLE IF NOT EXISTS rescue_media (
    case_id  UUID NOT NULL REFERENCES rescue_cases (case_id) ON DELETE CASCADE,
    media_id UUID NOT NULL REFERENCES media_files (media_id) ON DELETE CASCADE,
    PRIMARY KEY (case_id, media_id)
);

-- ── Adoption ────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS adoption_applications (
    application_id  UUID PRIMARY KEY,
    pet_id          UUID REFERENCES pets (pet_id),
    applicant_id    UUID REFERENCES users (user_id),
    organization_id UUID REFERENCES organizations (organization_id),
    status          VARCHAR(50),
    note            TEXT,
    experience      TEXT,
    live_condition  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by      UUID,
    decided_at      TIMESTAMPTZ,
    decided_by      UUID REFERENCES users (user_id),
    updated_at      TIMESTAMPTZ,
    updated_by      UUID,
    is_deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at      TIMESTAMPTZ,
    deleted_by      UUID
);

CREATE INDEX IF NOT EXISTS idx_adoption_pet       ON adoption_applications (pet_id);
CREATE INDEX IF NOT EXISTS idx_adoption_applicant ON adoption_applications (applicant_id);
CREATE INDEX IF NOT EXISTS idx_adoption_status    ON adoption_applications (status);

-- ── Posts & Media ───────────────────────────────────────

CREATE TABLE IF NOT EXISTS posts (
    post_id        UUID PRIMARY KEY,
    author_id      UUID REFERENCES users (user_id),
    rescue_case_id UUID REFERENCES rescue_cases (case_id),
    content        TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by     UUID,
    updated_at     TIMESTAMPTZ,
    updated_by     UUID,
    is_deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at     TIMESTAMPTZ,
    deleted_by     UUID
);

CREATE INDEX IF NOT EXISTS idx_posts_author     ON posts (author_id);
CREATE INDEX IF NOT EXISTS idx_posts_rescue     ON posts (rescue_case_id);
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts (created_at);

CREATE TABLE IF NOT EXISTS post_media (
    post_id  UUID NOT NULL REFERENCES posts (post_id) ON DELETE CASCADE,
    media_id UUID NOT NULL REFERENCES media_files (media_id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, media_id)
);

-- ── Tags ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tags (
    tag_id      UUID PRIMARY KEY,
    code        VARCHAR(100) UNIQUE,
    name        VARCHAR(255),
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  UUID,
    updated_at  TIMESTAMPTZ,
    updated_by  UUID,
    is_deleted  BOOLEAN     NOT NULL DEFAULT FALSE,
    deleted_at  TIMESTAMPTZ,
    deleted_by  UUID
);

CREATE TABLE IF NOT EXISTS post_tags (
    post_id UUID NOT NULL REFERENCES posts (post_id) ON DELETE CASCADE,
    tag_id  UUID NOT NULL REFERENCES tags (tag_id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_post_tags_tag ON post_tags (tag_id);

-- ── Audit Logs ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS audit_logs (
    log_id      UUID PRIMARY KEY,
    entity_type VARCHAR(100) NOT NULL,
    entity_id   VARCHAR(100) NOT NULL,
    action      VARCHAR(50)  NOT NULL,
    actor_id    UUID REFERENCES users (user_id),
    old_value   JSONB,
    new_value   JSONB,
    ip_address  VARCHAR(50),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_entity  ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_actor   ON audit_logs (actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs (created_at);

-- ── Seed default roles ──────────────────────────────────

INSERT INTO roles (code, name, description) VALUES
    ('USER',   'User',                'Default registered user'),
    ('ADMIN',  'Admin',               'System administrator'),
    ('MEMBER', 'Organization Member', 'Member of an organization (shelter, vet center, etc.)')
ON CONFLICT (code) DO NOTHING;
