-- ============================================================
-- V1: Initial schema — Pet Rescue API
-- ============================================================

-- ── Users & Auth ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS users (
    user_id       UUID PRIMARY KEY,
    username      VARCHAR(255) UNIQUE NOT NULL,
    email         VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255),
    avatar_url    TEXT,
    status        VARCHAR(50)  NOT NULL DEFAULT 'PENDING_VERIFICATION',
    email_verified BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);
CREATE INDEX IF NOT EXISTS idx_users_email  ON users (email);

CREATE TABLE IF NOT EXISTS roles (
    role_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) UNIQUE NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id     UUID    NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    role_id     INTEGER NOT NULL REFERENCES roles (role_id) ON DELETE CASCADE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS permissions (
    permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource      VARCHAR(50) NOT NULL,
    action        VARCHAR(50) NOT NULL,
    code          VARCHAR(120) UNIQUE,
    description   TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (resource, action)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       INTEGER NOT NULL REFERENCES roles (role_id) ON DELETE CASCADE,
    permission_id INTEGER NOT NULL REFERENCES permissions (permission_id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID         NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    token       VARCHAR(512) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user  ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_token ON refresh_tokens (token);

CREATE TABLE IF NOT EXISTS email_verification_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID         NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    token       VARCHAR(512) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ  NOT NULL,
    used        BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_reputations (
    user_id    UUID PRIMARY KEY REFERENCES users (user_id) ON DELETE CASCADE,
    score      INTEGER     DEFAULT 0,
    level      VARCHAR(50),
    updated_at TIMESTAMPTZ
);

-- ── Organizations ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS organizations (
    organization_id UUID PRIMARY KEY,
    name            VARCHAR(255),
    type            VARCHAR(50),
    address         TEXT,
    phone           VARCHAR(50),
    latitude        DOUBLE PRECISION,
    longitude       DOUBLE PRECISION,
    status          VARCHAR(50),
    created_at      TIMESTAMPTZ,
    created_by      UUID REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS shelters (
    organization_id UUID REFERENCES organizations (organization_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vet_centers (
    organization_id UUID REFERENCES organizations (organization_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS organization_members (
    organization_id UUID        NOT NULL REFERENCES organizations (organization_id) ON DELETE CASCADE,
    user_id         UUID        NOT NULL REFERENCES users (user_id) ON DELETE CASCADE,
    role            VARCHAR(30),
    joined_at       TIMESTAMPTZ,
    status          VARCHAR(50),
    PRIMARY KEY (organization_id, user_id)
);

-- ── Pets ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS pets (
    id            UUID PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    species       VARCHAR(50)  NOT NULL,
    breed         VARCHAR(100),
    age           INTEGER,
    gender        VARCHAR(20),
    color         VARCHAR(50),
    weight        NUMERIC(5,2),
    description   TEXT,
    status        VARCHAR(20)  NOT NULL,
    health_status VARCHAR(30),
    is_vaccinated BOOLEAN      NOT NULL DEFAULT FALSE,
    is_neutered   BOOLEAN      NOT NULL DEFAULT FALSE,
    rescue_date   DATE,
    rescue_location VARCHAR(255),
    shelter_id    UUID,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    VARCHAR(255),
    updated_at    TIMESTAMPTZ,
    updated_by    VARCHAR(255),
    is_deleted    BOOLEAN      NOT NULL DEFAULT FALSE,
    deleted_at    TIMESTAMPTZ,
    deleted_by    VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS idx_pet_species ON pets (species);
CREATE INDEX IF NOT EXISTS idx_pet_status  ON pets (status);
CREATE INDEX IF NOT EXISTS idx_pet_shelter ON pets (shelter_id);

CREATE TABLE IF NOT EXISTS pet_images (
    pet_id    UUID         NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    image_url VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS pet_ownerships (
    pet_id     UUID        NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    owner_type VARCHAR(20),
    owner_id   UUID,
    from_time  TIMESTAMPTZ NOT NULL,
    to_time    TIMESTAMPTZ,
    PRIMARY KEY (pet_id, from_time)
);

CREATE TABLE IF NOT EXISTS pet_medical_records (
    record_id   UUID PRIMARY KEY,
    pet_id      UUID NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    description TEXT,
    vaccine     VARCHAR(255),
    diagnosis   TEXT,
    record_date TIMESTAMPTZ,
    created_by  UUID REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS pet_locations (
    location_id UUID PRIMARY KEY,
    pet_id      UUID NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION,
    source      VARCHAR(50),
    recorded_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS pet_caretaker_assignments (
    assignment_id UUID PRIMARY KEY,
    pet_id        UUID        NOT NULL REFERENCES pets (id) ON DELETE CASCADE,
    organization_id UUID      NOT NULL REFERENCES organizations (organization_id),
    caretaker_id  UUID        NOT NULL REFERENCES users (user_id),
    role          VARCHAR(30),
    assigned_at   TIMESTAMPTZ,
    unassigned_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_pet_caretaker ON pet_caretaker_assignments (pet_id, caretaker_id, assigned_at);

-- ── Adoption ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS adoption_applications (
    application_id UUID PRIMARY KEY,
    pet_id         UUID REFERENCES pets (id),
    applicant_id   UUID REFERENCES users (user_id),
    organization_id UUID REFERENCES organizations (organization_id),
    status         VARCHAR(50),
    note           TEXT,
    created_at     TIMESTAMPTZ,
    decided_at     TIMESTAMPTZ,
    decided_by     UUID REFERENCES users (user_id)
);

-- ── Rescue Cases ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS rescue_cases (
    case_id         UUID PRIMARY KEY,
    pet_id          UUID REFERENCES pets (id),
    reported_by     UUID REFERENCES users (user_id),
    organization_id UUID REFERENCES organizations (organization_id),
    status          VARCHAR(50),
    reported_at     TIMESTAMPTZ
);

-- ── Posts & Media ─────────────────────────────────────────

CREATE TABLE IF NOT EXISTS posts (
    post_id        UUID PRIMARY KEY,
    author_id      UUID REFERENCES users (user_id),
    rescue_case_id UUID REFERENCES rescue_cases (case_id),
    content        TEXT,
    created_at     TIMESTAMPTZ,
    updated_at     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS media_files (
    media_id    UUID PRIMARY KEY,
    uploader_id UUID REFERENCES users (user_id),
    url         TEXT,
    type        VARCHAR(20),
    created_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS post_media (
    post_id  UUID NOT NULL REFERENCES posts (post_id) ON DELETE CASCADE,
    media_id UUID NOT NULL REFERENCES media_files (media_id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, media_id)
);

CREATE TABLE IF NOT EXISTS pet_diary (
    pet_id   UUID REFERENCES pets (id) ON DELETE CASCADE,
    media_id UUID REFERENCES media_files (media_id) ON DELETE CASCADE
);

-- ── Tags ──────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS tags (
    tag_id      UUID PRIMARY KEY,
    code        VARCHAR(100) UNIQUE,
    name        VARCHAR(255),
    description TEXT,
    created_at  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS post_tags (
    post_id UUID NOT NULL REFERENCES posts (post_id) ON DELETE CASCADE,
    tag_id  UUID NOT NULL REFERENCES tags (tag_id) ON DELETE CASCADE,
    PRIMARY KEY (post_id, tag_id)
);

-- ── Seed default roles ────────────────────────────────────

INSERT INTO roles (code, name, description) VALUES
    ('USER',  'User',  'Default registered user'),
    ('ADMIN', 'Admin', 'System administrator'),
    ('MEMBER', 'Organization Member', 'Member of an organization (shelter, vet center, etc.)')
ON CONFLICT (code) DO NOTHING;
